CREATE TABLE SEDE (
COD_SEDE NUMBER (6),
NOMBRE_SEDE VARCHAR (30),
DIRECCION VARCHAR (25),
CONSTRAINT SEDE_PK PRIMARY KEY (COD_SEDE)
);

CREATE TABLE DEPARTAMENTO (
COD_DEPARTAMENTO NUMBER (6),
NOMBRE_DEPARTAMENTO VARCHAR (30),
UBICACION VARCHAR (25),
COD_SEDE NUMBER (6),
CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY (COD_SEDE) REFERENCES SEDE(COD_SEDE),
CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY (COD_DEPARTAMENTO)
);

CREATE TABLE PROGRAMADOR (
  SECUENCIA VARCHAR2(20) NOT NULL,
  NOMBRE_PROGRAMADOR VARCHAR2(30) NOT NULL,
  AP1_PROGRAMADOR VARCHAR2(35) NOT NULL,
  AP2_PROGRAMADOR VARCHAR2(35) NULL,
  CUENTA VARCHAR2(28) NOT NULL,
  DIRECCION VARCHAR2(30) NOT NULL,
  TELEFONO NUMBER(9) NOT NULL,
  TIPO VARCHAR2(25) NOT NULL,
  MENTOR VARCHAR2(30) NOT NULL,
  COD_DEPARTAMENTO NUMBER(6) NOT NULL,
  CONSTRAINT FK_DEPARTAMENTO2 FOREIGN KEY (COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO(COD_DEPARTAMENTO),
  CONSTRAINT FK_PROGRAMADOR FOREIGN KEY (MENTOR) REFERENCES PROGRAMADOR(SECUENCIA),
  CONSTRAINT PROGRAMADOR_PK PRIMARY KEY (SECUENCIA)
);

CREATE TABLE EQUIPO (
COD_EQUIPO VARCHAR (30) NOT NULL,
DESCRIPCION VARCHAR (50) NOT NULL,
SECUENCIA VARCHAR (30) NOT NULL,
CONSTRAINT FK_PROGRAMADOR_E FOREIGN KEY (SECUENCIA) REFERENCES PROGRAMADOR(SECUENCIA),
CONSTRAINT EQUIPO_PK PRIMARY KEY (COD_EQUIPO)
);

CREATE TABLE EQUIPO_PROG(
SECUENCIA VARCHAR (30) NOT NULL,
COD_EQUIPO VARCHAR(30) NOT NULL,
CONSTRAINT FK_PROGRAMADOR_EP FOREIGN KEY (SECUENCIA) REFERENCES PROGRAMADOR(SECUENCIA),
CONSTRAINT FK_EQUIPO FOREIGN KEY (COD_EQUIPO) REFERENCES EQUIPO(COD_EQUIPO),
CONSTRAINT EQUIPO_PROG_PK PRIMARY KEY (SECUENCIA, COD_EQUIPO)
);

CREATE TABLE PROYECTO (
FECHA_INI DATE NOT NULL,
DESCRIPCION_PROYECTO VARCHAR (30),
FECHA_FIN DATE NULL,
PARTEPROY DATE,
COD_EQUIPO VARCHAR (30),
CONSTRAINT FK_EQUIPO_P FOREIGN KEY (COD_EQUIPO) REFERENCES EQUIPO(COD_EQUIPO), 
CONSTRAINT PROYECTO_PK PRIMARY KEY (FECHA_INI) ,
CONSTRAINT FK_PROYECTO FOREIGN KEY (PARTEPROY) REFERENCES PROYECTO(FECHA_INI)

);

ALTER TABLE EQUIPO_PROG
ADD CONSTRAINT FK_EQUIPO FOREIGN KEY (COD_EQUIPO) REFERENCES EQUIPO(COD_EQUIPO)  ON DELETE CASCADE;

