CREATE TABLE DATOS_PERSONALES(
DNI VARCHAR(9) NOT NULL,
NOMBRE VARCHAR (30) NOT NULL,
AP1 VARCHAR (35) NOT NULL,
AP2 VARCHAR (35) NULL,
EMAIL VARCHAR (40) NULL,
TELEFONO NUMBER (9)NULL,
TIPO VARCHAR (20),
CONSTRAINT DATOS_PERSONALES_PK PRIMARY KEY (DNI),
CONSTRAINT CHECK_TIPO CHECK(TIPO IN ('DIRECTOR','COMERCIAL','VENDEDOR','CLIENTE'))
);

CREATE TABLE DIRECTOR (
DNI_DIRECTOR VARCHAR(9) NOT NULL,
CONSTRAINT FK_DATOSPERSONALES FOREIGN KEY (DNI_DIRECTOR) REFERENCES DATOS_PERSONALES(DNI),
CONSTRAINT DIRECTOR_PK PRIMARY KEY (DNI_DIRECTOR) 
);

CREATE TABLE COMERCIAL (
DNI_COMERCIAL VARCHAR(9) NOT NULL,
COMISION NUMBER (5) NOT NULL, 
CONSTRAINT FK_DATOSPERSONALESC FOREIGN KEY (DNI_COMERCIAL) REFERENCES DATOS_PERSONALES(DNI),
CONSTRAINT COMERCIAL_PK PRIMARY KEY (DNI_COMERCIAL) 
);

CREATE TABLE OFICINA (
COD_OFICINA VARCHAR(4) NOT NULL,
DIRECCION VARCHAR (20) NOT NULL,
TELEFONO NUMBER (9) NOT NULL,
DNI_DIRECTOR VARCHAR(9) NOT NULL,
DNI_COMERCIAL VARCHAR(9) NOT NULL,
CONSTRAINT FK_DIRECTOR FOREIGN KEY (DNI_DIRECTOR) REFERENCES DIRECTOR(DNI_DIRECTOR),
CONSTRAINT FK_COMERCIAL FOREIGN KEY (DNI_COMERCIAL) REFERENCES COMERCIAL(DNI_COMERCIAL)
);

ALTER TABLE OFICINA ADD CONSTRAINT OFICINA_PK PRIMARY KEY (COD_OFICINA);

CREATE TABLE VENDEDOR (
DNI_VENDEDOR VARCHAR (9) NOT NULL,
TURNO VARCHAR (6) NOT NULL,
COD_OFICINA VARCHAR (4) NOT NULL,
CONSTRAINT FK_OFICINA FOREIGN KEY (COD_OFICINA) REFERENCES OFICINA(COD_OFICINA),
CONSTRAINT CHECK_TURNO CHECK(TURNO IN ('MAÑANA' , 'TARDE')),
CONSTRAINT VENDEDOR_PK PRIMARY KEY (DNI_VENDEDOR)
);

CREATE TABLE CLIENTE (
DNI_CLIENTE VARCHAR (9),
TARJETA NUMBER (13),
CONSTRAINT FK_DATOSPERSONALESCL FOREIGN KEY (DNI_CLIENTE) REFERENCES DATOS_PERSONALES(DNI),
CONSTRAINT CLIENTE_PK PRIMARY KEY (DNI_CLIENTE)
);

CREATE TABLE VENTA(
FECHA DATE,
COD_VENTA NUMBER(14),
DNI_VENDEDOR VARCHAR (9),
DNI_CLIENTE VARCHAR (9),
CONSTRAINT FK_VENDEDOR FOREIGN KEY (DNI_VENDEDOR) REFERENCES VENDEDOR(DNI_VENDEDOR), 
CONSTRAINT FK_CLIENTE FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE (DNI_CLIENTE),
CONSTRAINT VENTA_PK PRIMARY KEY (FECHA,COD_VENTA)
);

CREATE TABLE EDITORIAL (
CIF VARCHAR (10),
RAZON_SOCIAL VARCHAR (20),
DIRECCION VARCHAR (30),
SITIO_WEB VARCHAR (40),
CORREO VARCHAR (40),
CONSTRAINT EDITORIAL_PK PRIMARY KEY (CIF)
);

CREATE TABLE LIBRO (
ISBN NUMBER (20),
DESCRIPCION VARCHAR (40),
NUM_PAGS NUMBER (4),
PRECIO NUMBER (4),
AUTOR VARCHAR (19),
TEMATICA VARCHAR (20),
CONSTRAINT CHECK_TEMATICA CHECK (TEMATICA IN ('POLICIACA', 'ROMANTICA' , 'MISTERIO', 'JUVENIL')),
CONSTRAINT ISBN_PK PRIMARY KEY (ISBN)
);

CREATE TABLE LINEA_VENTA (
ISBN NUMBER (20),
FECHA DATE,
COD_VENTA NUMBER (14),
CANTIDAD NUMBER (2),
CONSTRAINT FK_LIBRO FOREIGN KEY (ISBN) REFERENCES LIBRO(ISBN),
CONSTRAINT LINEA_VENTA PRIMARY KEY (ISBN,FECHA,COD_VENTA)
);  

CREATE TABLE TIPODP (
COD_TIPO NUMBER (4),
DESCRIPCION VARCHAR (200),
CONSTRAINT TIPODP_PK PRIMARY KEY (COD_TIPO)
);

CREATE TABLE TURNO (
COD_TURNO NUMBER (8),
DESCRIPCION VARCHAR (200),
CONSTRAINT TURNO_PK PRIMARY KEY (COD_TURNO)
);

ALTER TABLE VENDEDOR DROP COLUMN TURNO;

ALTER TABLE VENDEDOR ADD COD_TURNO NUMBER(4);
ALTER TABLE VENDEDOR ADD CONSTRAINT FK_VENDEDOR1 FOREIGN KEY (COD_TURNO) REFERENCES TURNO(COD_TURNO);

CREATE TABLE TEMATICA (
COD_TEMATICA NUMBER(3),
DESCRIPCION VARCHAR (200),
CONSTRAINT TEMATICA_PK PRIMARY KEY (COD_TEMATICA)
);

ALTER TABLE LIBRO DROP COLUMN TEMATICA;

ALTER TABLE LIBRO ADD COD_TEMATICA NUMBER (3);
ALTER TABLE LIBRO ADD CONSTRAINT FK_TEMATICA FOREIGN KEY (COD_TEMATICA) REFERENCES TEMATICA(COD_TEMATICA);
