INSERT INTO CONDUCTOR(DNI, NOMBRE, PRAPELLIDO, SGAPELLIDO, NUM_EMPLEADO) VALUES
('38607982N', 'LUCIA', 'GARCIA', 'MEDINA', 526987);
INSERT INTO CONDUCTOR(DNI, NOMBRE, PRAPELLIDO, SGAPELLIDO, NUM_EMPLEADO) VALUES
('31207102C', 'BEATRIZ', 'MENDEZ', 'GARCIA', 445879);
INSERT INTO CONDUCTOR(DNI, NOMBRE, PRAPELLIDO, SGAPELLIDO, NUM_EMPLEADO) VALUES
('99207123L', 'DAVID', 'PEREZ', 'HOYO', 362201);
INSERT INTO CONDUCTOR(DNI, NOMBRE, PRAPELLIDO, SGAPELLIDO, NUM_EMPLEADO) VALUES
('45204004G', 'DANIEL', 'SANTOS', 'PEREZ', 899630);


--A
SELECT *
FROM CONDUCTOR
WHERE PRAPELLIDO = ('PEREZ')
AND NOMBRE != ('DAVID');

--B
SELECT * 
FROM CONDUCTOR 
WHERE NOMBRE LIKE ('L%')
AND SGAPELLIDO IS NOT NULL;

--C
SELECT NOMBRE 
FROM CONDUCTOR
WHERE PRAPELLIDO IN ('LOPEZ','GARCIA')
AND DNI NOT LIKE ('%L');

--D
SELECT *
FROM CONDUCTOR
ORDER BY PRAPELLIDO ASC;

--E ---------------------------------------------------------------------
SELECT *
FROM CONDUCTOR
ORDER BY PRAPELLIDO ASC, SGAPELLIDO ASC;

--F
SELECT *
FROM CONDUCTOR 
WHERE PRAPELLIDO != ('PEREZ')
AND SGAPELLIDO !=('PEREZ');

--G
SELECT DISTINCT C.DNI 
FROM CONDUCTOR C
JOIN VIAJES V ON C.DNI = V.DNI_CONDUCTOR;

--H
SELECT DISTINCT DESTINO
FROM VIAJES
ORDER BY DESTINO ASC;

--------------------------------------------------------------------------------
ALTER TABLE AUTOBUS ADD PRECIO NUMBER(6);


UPDATE AUTOBUS
SET PRECIO = 485000
WHERE MATRICULA = '4598DLM';

UPDATE AUTOBUS
SET PRECIO = 712500
WHERE MATRICULA = '2526LMX';

UPDATE AUTOBUS
SET PRECIO = 573250
WHERE MATRICULA = '2130HGF';

UPDATE AUTOBUS
SET PRECIO= 821750
WHERE MATRICULA = '9995GVC';

--------------------------------------------------------------------------------

SELECT MAX(PRECIO)
FROM AUTOBUS;

SELECT PRECIO-------------------------------------------------------------------
FROM (SELECT PRECIO FROM AUTOBUS
ORDER BY PRECIO DESC)
WHERE ROWNUM = 1;

--------------------------------------------------------------------------------

SELECT *
FROM CONDUCTOR C
JOIN VIAJES V ON C.DNI = V.DNI_CONDUCTOR
WHERE DESTINO NOT LIKE ('L%')
ORDER BY NUM_EMPLEADO ASC;


SELECT * 
FROM VIAJES V
JOIN CONDUCTOR C ON V.DNI_CONDUCTOR = C.DNI
WHERE C.NUM_EMPLEADO < 700000 
AND SGAPELLIDO != ('PEREZ');


SELECT C.NOMBRE, C.PRAPELLIDO---------------------------------------------------
FROM CONDUCTOR C
LEFT OUTER JOIN VIAJES V ON C.DNI = V.DNI_CONDUCTOR;


SELECT COUNT (*)
FROM VIAJES
WHERE TIPO = ('PRIVADO');

SELECT MAX(A.PRECIO),MIN(A.PRECIO),AVG(A.PRECIO)
FROM AUTOBUS A
JOIN VIAJES V ON A.MATRICULA = V.MATRICULA_AUTOBUS;

SELECT C.NOMBRE, C.PRAPELLIDO, COUNT(V.DNI_CONDUCTOR) AS NUMERO_VIAJES
FROM CONDUCTOR C
JOIN VIAJES V ON C.DNI = V.DNI_CONDUCTOR
GROUP BY C.NOMBRE, C.PRAPELLIDO
HAVING COUNT(V.DNI_CONDUCTOR) > 1;
--------------------

SELECT *
FROM AUTOBUS
WHERE PRECIO > (SELECT A.PRECIO  FROM AUTOBUS A JOIN VIAJES V ON A.MATRICULA = V.MATRICULA_AUTOBUS WHERE V.DNI_CONDUCTOR = (SELECT DNI FROM CONDUCTOR WHERE NOMBRE = ('PEDRO')));

SELECT * FROM AUTOBUS WHERE PRECIO <=ALL (SELECT PRECIO FROM AUTOBUS) ;

SELECT DISTINCT C.NOMBRE
FROM CONDUCTOR C
JOIN VIAJES V ON C.DNI = V.DNI_CONDUCTOR
WHERE NOMBRE !=('VERONICA');

SELECT *
FROM AUTOBUS 
WHERE PRECIO > (SELECT AVG(A.PRECIO) FROM AUTOBUS A JOIN VIAJES V ON A.MATRICULA = V.MATRICULA_AUTOBUS WHERE V.DNI_CONDUCTOR = (SELECT DNI FROM CONDUCTOR WHERE NOMBRE = ('LUCAS')))



