CREATE TABLE EMPLEADOS(
CLAVE_EMP VARCHAR (5),
NOMBRE VARCHAR(30),
APELLIDOS VARCHAR (30),
CLAVE_DPTO NUMBER (1),

CONSTRAINT EMPLEADOS_PK PRIMARY KEY(CLAVE_EMP),
CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY(CLAVE_DPTO)REFERENCES DEPARTAMENTO(CLAVE_DPTO)
);

CREATE TABLE DEPARTAMENTO(
CLAVE_DPTO NUMBER (1),
NOMBRE VARCHAR(30),
PRESUPUESTO NUMBER (5),

CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY (CLAVE_DPTO)
);

--INSERTS EMPLEADO 
INSERT INTO EMPLEADOS (CLAVE_EMP, NOMBRE,APELLIDOS,CLAVE_DPTO) VALUES ('EMP01','ARMANDO','LOPEZ',2);
INSERT INTO EMPLEADOS (CLAVE_EMP, NOMBRE,APELLIDOS,CLAVE_DPTO) VALUES ('EMP02','TATIANA','VARGAS',1);
INSERT INTO EMPLEADOS (CLAVE_EMP, NOMBRE,APELLIDOS,CLAVE_DPTO) VALUES ('EMP03','LAURA','GARCIA',3);
INSERT INTO EMPLEADOS (CLAVE_EMP, NOMBRE,APELLIDOS,CLAVE_DPTO) VALUES ('EMP04','JUAN','PEREZ',4);
INSERT INTO EMPLEADOS (CLAVE_EMP, NOMBRE,APELLIDOS,CLAVE_DPTO) VALUES ('EMP05','IVAN','LOPEZ',4);
INSERT INTO EMPLEADOS (CLAVE_EMP, NOMBRE,APELLIDOS,CLAVE_DPTO) VALUES ('EMP06','MARGARITA','HERNANDEZ',1);
INSERT INTO EMPLEADOS (CLAVE_EMP, NOMBRE,APELLIDOS,CLAVE_DPTO) VALUES ('EMP07','JESUS','PEREZ',3);
INSERT INTO EMPLEADOS (CLAVE_EMP, NOMBRE,APELLIDOS,CLAVE_DPTO) VALUES ('EMP08','TOÑO','FLORES',2);
INSERT INTO EMPLEADOS (CLAVE_EMP, NOMBRE,APELLIDOS,CLAVE_DPTO) VALUES ('EMP09','JUAN','LOPEZ',4);
INSERT INTO EMPLEADOS (CLAVE_EMP, NOMBRE,APELLIDOS,CLAVE_DPTO) VALUES ('EMP10','JOSE','HERNANDEZ',5);

--INSERTS DEPARTAMENTO 
INSERT INTO DEPARTAMENTO (CLAVE_DPTO, NOMBRE,PRESUPUESTO) VALUES (1,'PERSONAL',80000);
INSERT INTO DEPARTAMENTO (CLAVE_DPTO, NOMBRE,PRESUPUESTO) VALUES (2,'ALAMACEN',70000);
INSERT INTO DEPARTAMENTO (CLAVE_DPTO, NOMBRE,PRESUPUESTO) VALUES (3,'CONTABILIDAD',60000);
INSERT INTO DEPARTAMENTO (CLAVE_DPTO, NOMBRE,PRESUPUESTO) VALUES (4,'MANUFACTURA',50000);
INSERT INTO DEPARTAMENTO (CLAVE_DPTO, NOMBRE,PRESUPUESTO) VALUES (5,'EMPAQUE',30000);


-----------------------------------------------------------------------------------------------

--A
SELECT NOMBRE,APELLIDOS
FROM EMPLEADOS;

--B
SELECT DISTINCT APELLIDOS
FROM EMPLEADOS;

--C
SELECT *
FROM EMPLEADOS
WHERE APELLIDOS =('LOPEZ');

--D
SELECT E.NOMBRE, E.APELLIDOS, D.NOMBRE AS NOMBRE_DEPARTAMENTO
FROM EMPLEADOS E
JOIN DEPARTAMENTO D ON E.CLAVE_DPTO = D.CLAVE_DPTO
WHERE E.CLAVE_EMP IN (
    SELECT CLAVE_EMP
    FROM EMPLEADOS
    WHERE NOMBRE NOT LIKE '%JUAN%' AND NOMBRE NOT LIKE '%IVAN%' AND NOMBRE NOT LIKE '%TOÑO%'
);



--E
SELECT *
FROM EMPLEADOS 
WHERE APELLIDOS = ('LOPEZ')
OR APELLIDOS =('PEREZ');

--F
SELECT NOMBRE, CLAVE_EMP
FROM EMPLEADOS
WHERE CLAVE_DPTO = (4);

--G
SELECT NOMBRE,APELLIDOS
FROM EMPLEADOS 
WHERE APELLIDOS LIKE ('H%');

--H 
SELECT *
FROM DEPARTAMENTO
WHERE PRESUPUESTO BETWEEN 50000 AND 70000;

--I
SELECT NOMBRE,APELLIDOS
FROM EMPLEADOS
WHERE CLAVE_DPTO =(3);

--J
SELECT E.NOMBRE, E.APELLIDOS, D.NOMBRE AS NOMBRE_DPTO
FROM EMPLEADOS E
JOIN DEPARTAMENTO D ON E.CLAVE_DPTO = D.CLAVE_DPTO;

--K
--AVG

--L
SELECT *--E.NOMBRE AS NOMBRE_EMPLEADO
FROM EMPLEADOS E 
JOIN DEPARTAMENTO D ON E.CLAVE_DPTO = D.CLAVE_DPTO
WHERE D.NOMBRE = ('MANUFACTURA');

