--A
SELECT DNI 
FROM PROFESOR P
JOIN DEPARTAMENTO D ON P.CODDEP = D.CODDEP;

SELECT DNI 
FROM PROFESOR P
JOIN DEPARTAMENTO D USING (CODDEP);

--B
SELECT NOMBRE,PRAPELLIDO 
FROM ALUMNO A 
JOIN ALUMBIL B ON A.DNI = B.DNI
WHERE UPPER (LUGAR) IN ('MADRID','BARCELONA');

SELECT A.NOMBRE,A.PRAPELLIDO 
FROM ALUMNO A 
JOIN ALUMBIL B USING (DNI)
WHERE UPPER (LUGAR) IN ('MADRID','BARCELONA');

--C
SELECT AL.NOMBRE,AL.PRAPELLIDO,AL.SGAPELLIDO
FROM ALUMNO AL 
JOIN MATRICULA M ON AL.DNI= M.DNI 
JOIN ASIGNATURA A ON M.CODASIG = M.CODASIG;

SELECT AL.NOMBRE,AL.PRAPELLIDO,AL.SGAPELLIDO
FROM ALUMNO AL 
JOIN MATRICULA M USING (DNI) 
JOIN ASIGNATURA A USING (CODASIG);


--D
SELECT A.NOMBRE,A.PRAPELLIDO,A.SGAPELLIDO
FROM ALUMNO A
JOIN MATRICULA M ON A.DNI = M.DNI
JOIN ASIGNATURA AG ON M.CODASIG = AG.CODASIG
JOIN CICLO C ON AG.CODCICLO = C.CODCICLO;

SELECT A.NOMBRE,A.PRAPELLIDO,A.SGAPELLIDO
FROM ALUMNO A
JOIN MATRICULA M USING (DNI)
JOIN ASIGNATURA AG USING (CODASIG)
JOIN CICLO C USING (CODCICLO);


--E
SELECT AG.NOMBRE
FROM ASIGNATURA AG
JOIN IMPARTE I ON AG.CODASIG = I.CODASIG
JOIN PROFESOR P ON I.DNI = P.DNI
JOIN DEPARTAMENTO D ON P.CODDEP = D.CODDEP
JOIN MATRICULA M ON AG.CODASIG = M.CODASIG
JOIN ALUMNO AL ON M.DNI = AL.DNI
JOIN CICLO C ON AG.CODCICLO = C.CODCICLO;

SELECT AG.NOMBRE
FROM ASIGNATURA AG
JOIN IMPARTE I USING (CODASIG)
JOIN PROFESOR P USING (DNI)
JOIN DEPARTAMENTO D USING (CODDEP)
JOIN MATRICULA M USING (CODASIG)
JOIN ALUMNO AL USING (DNI)
JOIN CICLO C USING(CODCICLO);



