--5.4

--A
SELECT MAX(PRECIO)
FROM LIBROS;

--B
SELECT MIN(PRECIO) 
FROM LIBROS;

--C
SELECT MIN(FECHA_SAL)
FROM EDITA
WHERE DNI_TECNICO = ('443042293');

--D
SELECT MAX(FECHA_SAL)
FROM EDITA
WHERE DNI_TECNICO = ('29110302.');

--E
SELECT L.NUMPAG
FROM LIBRO L
JOIN TEMATICA T ON L.TEMATICA= T.TEMATICA
WHERE TEMATICA = ('NOVELA');

--F
SELECT L.NUMPAG
FROM LIBRO L
JOIN TEMATICA T ON L.TEMATICA = T.TEMATICA
WHERE TEMATICA IN ('INFANTIL','CIENTIFICA','NOVELA','COMICO');

--G
SELECT * 
FROM LIBRO L
JOIN TEMATICA T ON L.TEMATICA = T.TEMATICA
WHERE PRECIO BETWEEN 5 AND 15
AND TEMATICA = ('CIENTIFICO');