CREATE TABLE EMPLEADO (
DNI VARCHAR (9),
NOMBRE VARCHAR (30),
PRAPELLIDO VARCHAR(30),
SGAPELLIDO VARCHAR(30),
CIUDAD VARCHAR(30),

CONSTRAINT EMPLEADO_PK PRIMARY KEY (DNI)
);

INSERT INTO EMPLEADO (DNI,NOMBRE,PRAPELLIDO,SGAPELLIDO,CIUDAD) VALUES ('41200500','LUIS','GARCIA','RUIZ','MADRID');
INSERT INTO EMPLEADO (DNI,NOMBRE,PRAPELLIDO,SGAPELLIDO,CIUDAD) VALUES ('49138953','FRANCISCO','SANCHEZ','GARCIA','SEVILLA');
INSERT INTO EMPLEADO (DNI,NOMBRE,PRAPELLIDO,SGAPELLIDO,CIUDAD) VALUES ('87533912','ROSA','BLANCO','SANCHEZ','MADRID');
INSERT INTO EMPLEADO (DNI,NOMBRE,PRAPELLIDO,SGAPELLIDO,CIUDAD) VALUES ('43058284','MARIA','MARIN','VELASCO','BARCELONA');
INSERT INTO EMPLEADO (DNI,NOMBRE,PRAPELLIDO,SGAPELLIDO,CIUDAD) VALUES ('75931049','MARIA PILAR','GARCIA','MONTERO','VALENCIA');
INSERT INTO EMPLEADO (DNI,NOMBRE,PRAPELLIDO,SGAPELLIDO,CIUDAD) VALUES ('83456723','FERNANDO','MARIN','PEREZ','MALAGA');
INSERT INTO EMPLEADO (DNI,NOMBRE,PRAPELLIDO,SGAPELLIDO,CIUDAD) VALUES ('93576821','DOLORES','POSTIGO','SANCHEZ','PAMPLONA');
INSERT INTO EMPLEADO (DNI,NOMBRE,PRAPELLIDO,SGAPELLIDO,CIUDAD) VALUES ('57893098','JAVIER ANTONIO','LUQUE','RAMOS','SORIA');
INSERT INTO EMPLEADO (DNI,NOMBRE,PRAPELLIDO,SGAPELLIDO,CIUDAD) VALUES ('23567454','PEDRO','MUÑOZ','GONZALEZ','JAEN');
INSERT INTO EMPLEADO (DNI,NOMBRE,PRAPELLIDO,SGAPELLIDO,CIUDAD) VALUES ('23999090','ANGEL ALBERTO','PALACIOS','LARA','SALAMANCA');
INSERT INTO EMPLEADO (DNI,NOMBRE,PRAPELLIDO,SGAPELLIDO,CIUDAD) VALUES ('67394399','JOSEFA','CEA','PALACIOS','GRANADA');
INSERT INTO EMPLEADO (DNI,NOMBRE,PRAPELLIDO,SGAPELLIDO,CIUDAD) VALUES ('91234987','ALEJANDRO','CHAPARRO','MARIN','BARCELONA');
INSERT INTO EMPLEADO (DNI,NOMBRE,PRAPELLIDO,SGAPELLIDO,CIUDAD) VALUES ('81234987','ANTONIO','ALEGRE','GOMEZ','MADRID');
INSERT INTO EMPLEADO (DNI,NOMBRE,PRAPELLIDO,SGAPELLIDO,CIUDAD) VALUES ('41576329','PILAR','BURGOS','GARCIA','VALENCIA');
INSERT INTO EMPLEADO (DNI,NOMBRE,PRAPELLIDO,SGAPELLIDO,CIUDAD) VALUES ('39483123','DAVID ANTONIO','GOMEZ','RUIZ','SANTANDER');
INSERT INTO EMPLEADO (DNI,NOMBRE,PRAPELLIDO,SGAPELLIDO,CIUDAD) VALUES ('57938238','ANTONIO','GARCIA','MARIN','VALENCIA');
INSERT INTO EMPLEADO (DNI,NOMBRE,PRAPELLIDO,SGAPELLIDO,CIUDAD) VALUES ('49829384','MIGUEL','MARTIN','MUÑOZ','MADRID');
INSERT INTO EMPLEADO (DNI,NOMBRE,PRAPELLIDO,SGAPELLIDO,CIUDAD) VALUES ('43938000','ALICIA','SANCHEZ','ARAGON','MADRID');

---------------------------------------------------------------------------------------------------------------------------------------
--A
SELECT DNI
FROM EMPLEADO 
WHERE CIUDAD IN ('BARCELONA', 'MADRID', 'SEVILLA','MALAGA')
AND NOMBRE NOT IN ('ANTONIO','LUIS')
AND PRAPELLIDO !=('GARCIA');

--B
SELECT DNI
FROM EMPLEADO
WHERE CIUDAD !=('SEVILLA')
AND CIUDAD IN ('MADRID', 'BARCELONA')
AND NOMBRE LIKE ('M%');

-C
SELECT DNI
FROM EMPLEADO
WHERE CIUDAD = ('SEVILLA')
AND NOMBRE NOT LIKE ('M%');

--D
SELECT NOMBRE,PRAPELLIDO
FROM EMPLEADO
WHERE CIUDAD IN('VALENCIA','VIZCAYA')
AND CIUDAD LIKE ('%A')
ORDER BY PRAPELLIDO DESC;

--E
SELECT DNI
FROM EMPLEADO
WHERE CIUDAD = ('BARCELONA')
AND NOMBRE IN ('ANTONIO','LUIS','IVAN','PEDRO')
AND PRAPELLIDO IN ('GARCIA','CANTOS'); 

--F
SELECT NOMBRE, PRAPELLIDO
FROM EMPLEADO
WHERE DNI LIKE '%4%'
AND NOMBRE IN ('ROSA','LUIS','RAMON','ANTONIO')
ORDER BY PRAPELLIDO;

--G
SELECT DNI
FROM EMPLEADO
WHERE NOMBRE = ('ANTONIO')
AND PRAPELLIDO NOT LIKE ('%C%')
AND SGAPELLIDO IN ('GARCIA','GOMEZ','SANCHEZ')
ORDER BY SGAPELLIDO;

--H
SELECT DNI
FROM EMPLEADO
WHERE SGAPELLIDO IS NULL;


