--6.1
SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE imprimeValor( numero IN NUMBER) IS 
BEGIN 
DBMS_OUTPUT.PUT_LINE(numero);
END;


DECLARE 
NUMEROX NUMBER := 10;
BEGIN 
imprimeValor (NUMEROX);
END;