SET SERVEROUTPUT ON;


CREATE OR REPLACE PROCEDURE MAYOR (NUM1 IN NUMBER, NUM2 IN NUMBER, NUM3 IN NUMBER) IS
BEGIN 

IF NUM1 > NUM2 AND NUM1 >NUM3 THEN 
    DBMS_OUTPUT.PUT_LINE(NUM1);
    
ELSIF NUM2 > NUM1 AND NUM2 > NUM3 THEN 
     DBMS_OUTPUT.PUT_LINE(NUM2);
ELSE
     DBMS_OUTPUT.PUT_LINE(NUM3);
     END IF;

END;


DECLARE
NUM1 NUMBER:= 1;
NUM2 NUMBER := 3;
NUM3 NUMBER := 0;
BEGIN
MAYOR(NUM1,NUM2,NUM3);
END;