SET SERVEROUTPUT ON;
--6.2
CREATE OR REPLACE FUNCTION DIVISION (numero1 NUMBER, numero2 NUMBER) RETURN NUMBER IS
RESULTADO NUMBER;
BEGIN 
RESULTADO := numero1/numero2; 
return RESULTADO; 
END DIVISION;


DECLARE
RESULTADO_DIVISION NUMBER;
BEGIN
resultado_division := DIVISION(10,2);
DBMS_OUTPUT.PUT_LINE(RESULTADO_DIVISION);
END;