SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE INVERTIDO (P_INVERTIR IN VARCHAR) IS 
CADENA_INVERTIDA VARCHAR(200);
BEGIN
 FOR i IN REVERSE 1..LENGTH(P_INVERTIR) LOOP
        CADENA_INVERTIDA := CADENA_INVERTIDA || SUBSTR(P_INVERTIR, i, 1);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(CADENA_INVERTIDA);
END;



BEGIN
    INVERTIDO('Hola Mundo');
END;
