CREATE TABLE VIAJES (
NUM_EMPLEADO NUMBER(2),
FECHA VARCHAR(10));


INSERT INTO VIAJES (NUM_EMPLEADO,FECHA) VALUES (1,'12/03');
INSERT INTO VIAJES (NUM_EMPLEADO,FECHA) VALUES (2,'15/03');
INSERT INTO VIAJES (NUM_EMPLEADO,FECHA) VALUES (3,'19/03');


CREATE OR REPLACE PROCEDURE EMPLEADOBAJO (FECHA OUT VARCHAR) IS
FECHAEMP VARCHAR(100);
BEGIN
 SELECT FECHA INTO FECHAEMP
 FROM VIAJES
 WHERE NUM_EMPLEADO = (SELECT MIN(NUM_EMPLEADO) FROM VIAJES);
 
 FECHA :=FECHAEMP;
END;



SET SERVEROUTPUT ON;

DECLARE
    VFECHA VARCHAR(10);
BEGIN 
    EMPLEADOBAJO(VFECHA);
    DBMS_OUTPUT.PUT_LINE('La fecha del primer viaje es: ' || VFECHA);
END;

