SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE DIAS_SEMANA (NUMERO IN NUMBER) IS
BEGIN 
CASE NUMERO 
WHEN  1 THEN
 DBMS_OUTPUT.PUT_LINE('LUNES');
WHEN  2 THEN
 DBMS_OUTPUT.PUT_LINE('MARTES');
WHEN  3 THEN
 DBMS_OUTPUT.PUT_LINE('MIERCOLES');
WHEN  4 THEN
 DBMS_OUTPUT.PUT_LINE('JUEVES');
WHEN  5 THEN
 DBMS_OUTPUT.PUT_LINE('VIERNES');
WHEN 6 THEN
 DBMS_OUTPUT.PUT_LINE('SABADO');
WHEN  7 THEN
 DBMS_OUTPUT.PUT_LINE('DOMINGO');
 END CASE;
 END;


DECLARE 
NUMERO NUMBER := 4;
BEGIN
DIAS_SEMANA(NUMERO);
END;