DECLARE
VCODPOSTAL1 TOBJCODPOSTAL := TOBJCODPOSTAL('MADRID', 'MADRID');
VDOMICILIO1 TOBJDOMICILIO := TOBJDOMICILIO('AVENIDA', 'POSTIGO', 100, '1OA');
VNOMBRE1 TOBJNOMBRECOMPLETO := TOBJNOMBRECOMPLETO('ANGELA', 'NEGRO', 'CASTILLA');
VDATOSPERS1 TOBJDATOSPERS := TOBJDATOSPERS(VCODPOSTAL1, VNOMBRE1, VDOMICILIO1, TO_DATE('18/04/1991', 'DD/MM/YYYY'));

VCODPOSTAL2 TOBJCODPOSTAL := TOBJCODPOSTAL('MADRID', 'MADRID');
VDOMICILIO2 TOBJDOMICILIO := TOBJDOMICILIO('CALLE', 'SALADO', 114, '21O IZQ BLOQUE 2');
VNOMBRE2 TOBJNOMBRECOMPLETO := TOBJNOMBRECOMPLETO('TOM', 'OXLEY', NULL);
VDATOSPERS2 TOBJDATOSPERS := TOBJDATOSPERS(VCODPOSTAL2, VNOMBRE2, VDOMICILIO2, TO_DATE('30/05/1983', 'DD/MM/YYYY'));

BEGIN

    DBMS_OUTPUT.PUT_LINE('Datos de Ángela: ' || VDATOSPERS1.NOMBRECOMPLETO.NOMBRE || ' ' || VDATOSPERS1.NOMBRECOMPLETO.PRAPELLIDO || ' ' || VDATOSPERS1.NOMBRECOMPLETO.SGAPELLIDO);
    
    DBMS_OUTPUT.PUT_LINE('Datos de Tom: ' || VDATOSPERS2.NOMBRECOMPLETO.NOMBRE || ' ' || VDATOSPERS2.NOMBRECOMPLETO.PRAPELLIDO);
END;