
CREATE OR REPLACE TYPE TOBJCODPOSTAL AS OBJECT (
LOCALIDAD VARCHAR2(30),
PROVINCIA VARCHAR2(30),
MEMBER PROCEDURE INIT (SELF IN OUT NOCOPY TOBJCODPOSTAL, P_LOCALIDAD VARCHAR2, P_PROVINCIA VARCHAR2)
);


CREATE OR REPLACE TYPE BODY TOBJCODPOSTAL AS 
MEMBER PROCEDURE INIT (SELF IN OUT NOCOPY TOBJCODPOSTAL, P_LOCALIDAD VARCHAR2, P_PROVINCIA VARCHAR2) IS
BEGIN
SELF.LOCALIDAD := P_LOCALIDAD;
SELF.PROVINCIA := P_PROVINCIA;
END;
END;


CREATE OR REPLACE TYPE TOBJDOMICILIO AS OBJECT (
TIPOVIA VARCHAR2(30),
NOMBREVIA VARCHAR2(30),
NUMERO NUMBER(3),
RESTODOMICILIO VARCHAR2(30),
MEMBER PROCEDURE INIT (SELF IN OUT NOCOPY TOBJDOMICILIO, P_TIPOVIA VARCHAR2, P_NOMBREVIA VARCHAR2, P_NUMERO NUMBER, P_RESTODOMICILIO VARCHAR2)
);


CREATE OR REPLACE TYPE BODY TOBJDOMICILIO AS 
MEMBER PROCEDURE INIT (SELF IN OUT NOCOPY TOBJDOMICILIO, P_TIPOVIA VARCHAR2, P_NOMBREVIA VARCHAR2, P_NUMERO NUMBER, P_RESTODOMICILIO VARCHAR2) IS
BEGIN
SELF.TIPOVIA := P_TIPOVIA;
SELF.NOMBREVIA := P_NOMBREVIA;
SELF.NUMERO := P_NUMERO;
SELF.RESTODOMICILIO := P_RESTODOMICILIO;
END;
END;


CREATE OR REPLACE TYPE TOBJNOMBRECOMPLETO AS OBJECT (
NOMBRE VARCHAR2(30),
PRAPELLIDO VARCHAR2(35),
SGAPELLIDO VARCHAR2(35) NULL,
MEMBER PROCEDURE INIT (SELF IN OUT NOCOPY TOBJNOMBRECOMPLETO, P_NOMBRE VARCHAR2, P_PRAPELLIDO VARCHAR2, P_SGAPELLIDO VARCHAR2)
);


CREATE OR REPLACE TYPE BODY TOBJNOMBRECOMPLETO AS 
MEMBER PROCEDURE INIT (SELF IN OUT NOCOPY TOBJNOMBRECOMPLETO, P_NOMBRE VARCHAR2, P_PRAPELLIDO VARCHAR2, P_SGAPELLIDO VARCHAR2) IS
BEGIN
SELF.NOMBRE := P_NOMBRE;
SELF.PRAPELLIDO := P_PRAPELLIDO;
SELF.SGAPELLIDO := P_SGAPELLIDO;
END;
END;


CREATE OR REPLACE TYPE TOBJDATOSPERS AS OBJECT (
CODIGODP TOBJCODPOSTAL,
NOMBRECOMPLETO TOBJNOMBRECOMPLETO,
DOMICILIO TOBJDOMICILIO,
FECHA_NACIMIENTO DATE,
MEMBER PROCEDURE INIT (SELF IN OUT NOCOPY TOBJDATOSPERS, P_CODIGODP TOBJCODPOSTAL, P_NOMBRECOMPLETO TOBJNOMBRECOMPLETO, P_DOMICILIO TOBJDOMICILIO, P_FECHA_NACIMIENTO DATE)
);


CREATE OR REPLACE TYPE BODY TOBJDATOSPERS AS 
MEMBER PROCEDURE INIT (SELF IN OUT NOCOPY TOBJDATOSPERS, P_CODIGODP TOBJCODPOSTAL, P_NOMBRECOMPLETO TOBJNOMBRECOMPLETO, P_DOMICILIO TOBJDOMICILIO, P_FECHA_NACIMIENTO DATE) IS
BEGIN
ELF.CODIGODP := P_CODIGODP;
SELF.NOMBRECOMPLETO := P_NOMBRECOMPLETO;
SELF.DOMICILIO := P_DOMICILIO;
SELF.FECHA_NACIMIENTO := P_FECHA_NACIMIENTO;
END;
END;

DECLARE 
VCODPOSTAL TOBJCODPOSTAL := TOBJCODPOSTAL();
VDOMICILIO TOBJDOMICILIO := TOBJDOMICILIO();
VNOMBRE TOBJNOMBRECOMPLETO := TOBJNOMBRECOMPLETO();
VDATOSPERS TOBJDATOSPERS := TOBJDATOSPERS();
BEGIN 
VCODPOSTAL.INIT('MADRID', 'MADRID');
DBMS_OUTPUT.PUT_LINE('CODPOSTAL: ' || VCODPOSTAL.LOCALIDAD || ', ' || VCODPOSTAL.PROVINCIA);

VDOMICILIO.INIT('AVENIDA', 'POSTIGO', 100, '1OA');
DBMS_OUTPUT.PUT_LINE('DOMICILIO: ' || VDOMICILIO.TIPOVIA || ' ' || VDOMICILIO.NOMBREVIA || ' ' || VDOMICILIO.NUMERO || ', ' || VDOMICILIO.RESTODOMICILIO);

VNOMBRE.INIT('ANGELA', 'NEGRO', 'CASTILLA');
DBMS_OUTPUT.PUT_LINE('NOMBRE: ' || VNOMBRE.NOMBRE || ' ' || VNOMBRE.PRAPELLIDO || ' ' || VNOMBRE.SGAPELLIDO);

VDATOSPERS.INIT(VCODPOSTAL, VNOMBRE, VDOMICILIO, TO_DATE('18/04/1991', 'DD/MM/YYYY'));
DBMS_OUTPUT.PUT_LINE('DATOS PERSONALES: ' || VDATOSPERS.NOMBRECOMPLETO.NOMBRE || ' ' || VDATOSPERS.NOMBRECOMPLETO.PRAPELLIDO || ' ' || VDATOSPERS.NOMBRECOMPLETO.SGAPELLIDO || ', ' || VDATOSPERS.DOMICILIO.TIPOVIA || ' ' || VDATOSPERS.DOMICILIO.NOMBREVIA || ' ' || VDATOSPERS.DOMICILIO.NUMERO || ', ' || VDATOSPERS.DOMICILIO.RESTODOMICILIO || ', ' || TO_CHAR(VDATOSPERS.FECHA_NACIMIENTO, 'DD/MM/YYYY'));
END;

