
CREATE TYPE TOBJCODPOSTAL AS OBJECT(
    CODLOCALIDAD NUMBER(2),
    CODPROVINCIA NUMBER(3),
    MEMBER PROCEDURE CODIGO(P_CODPROVINCIA NUMBER, P_CODLOCALIDAD NUMBER)
);

CREATE OR REPLACE TYPE BODY TOBJCODPOSTAL AS
    MEMBER PROCEDURE CODIGO(P_CODPROVINCIA NUMBER, P_CODLOCALIDAD NUMBER) IS
    BEGIN
        CODLOCALIDAD := P_CODLOCALIDAD;
        CODPROVINCIA := P_CODPROVINCIA;
    END CODIGO;
END;


-- PL/SQL block
DECLARE 
    COD1 TOBJCODPOSTAL := TOBJCODPOSTAL(47, 12);
BEGIN 
    DBMS_OUTPUT.PUT_LINE(COD1.CODLOCALIDAD);
END;

