CREATE OR REPLACE TYPE PERSONA AS OBJECT (
VNOMBRE VARCHAR2(30),
VEDAD NUMBER(3),
CONSTRUCTOR FUNCTION PERSONA (VNOMBRE VARCHAR2, VEDAD NUMBER) RETURN SELF AS RESULT
);

CREATE OR REPLACE TYPE BODY PERSONA AS
CONSTRUCTOR FUNCTION PERSONA (VNOMBRE VARCHAR2, VEDAD NUMBER) RETURN SELF AS RESULT IS
BEGIN
SELF.NOMBRE := VNOMBRE;
SELF.EDAD := VEDAD;
RETURN SELF;
    END;
END;

DECLARE
V_PERSONA PERSONA;
BEGIN
V_PERSONA := PERSONA('PEPE', 34);
DBMS_OUTPUT.PUT_LINE(V_PERSONA.NOMBRE || ' ' || V_PERSONA.EDAD);
END;

