DECLARE
    PROFESOR_OBJ PROFESOR;
BEGIN
    PROFESOR_OBJ := NEW PROFESOR(
        NOMBRE => 'DOLORES SANCHEZ GOMEZ',
        DIRECCION => 'PLAZA ESPAÑA, 103, 1OA',
        CIUDAD => 'MADRID',
        PROVINCIA => 'MADRID',
        CP => '28003',
        FECHA_INCORPORACION => TO_DATE('01/09/2021', 'DD/MM/YYYY')
    );

    DBMS_OUTPUT.PUT_LINE('PROFESOR: ' || PROFESOR_OBJ.NOMBRE || ', DIRECCION: ' || PROFESOR_OBJ.DIRECCION || ', FECHA DE INCORPORACION: ' || TO_CHAR(PROFESOR_OBJ.FECHA_INCORPORACION, 'DD/MM/YYYY'));
END;

DECLARE
    ALUMNO_OBJ ALUMNO;
BEGIN
    ALUMNO_OBJ := NEW ALUMNO(
        NOMBRE => 'LUIS MARIN SOL',
        DIRECCION => 'CALLE LAGUNA, 12',
        CIUDAD => 'BOADILLA DEL MONTE',
        PROVINCIA => 'MADRID',
        CP => '28660',
        CALIFICACION_1TRIMESTRE => 4,
        CALIFICACION_2TRIMESTRE => 4,
        CALIFICACION_3TRIMESTRE => 5,
        CALIFICACION_4TRIMESTRE => 7
    );

    DBMS_OUTPUT.PUT_LINE('ALUMNO: ' || ALUMNO_OBJ.NOMBRE || ', DIRECCION: ' || ALUMNO_OBJ.DIRECCION || ', CALIFICACIONES: ' || ALUMNO_OBJ.CALIFICACION_1TRIMESTRE || ', ' || ALUMNO_OBJ.CALIFICACION_2TRIMESTRE || ', ' || ALUMNO_OBJ.CALIFICACION_3TRIMESTRE || ', ' || ALUMNO_OBJ.CALIFICACION_4TRIMESTRE);
END;

