CREATE OR REPLACE TYPE EMPLEADO AS OBJECT (
    DNI VARCHAR2(20),
    NOMBRE VARCHAR2(50),
    APELLIDO1 VARCHAR2(50),
    APELLIDO2 VARCHAR2(50),
    TELEFONO VARCHAR2(20)
)NOT FINAL;


CREATE OR REPLACE TYPE INSPECTOR UNDER EMPLEADO (
    ESPECIALIDAD VARCHAR2(50)
);


CREATE OR REPLACE TYPE POLICIA UNDER EMPLEADO (
    CATEGORIA VARCHAR2(50),
    SALARIO NUMBER(4),
    MEMBER FUNCTION calculaSalario RETURN NUMBER
);

CREATE OR REPLACE TYPE BODY POLICIA AS
    MEMBER FUNCTION calculaSalario RETURN NUMBER IS
    BEGIN
        IF (SELF.CATEGORIA = 'LOCAL') THEN
            RETURN SELF.SALARIO * 1.05;
        ELSIF (SELF.CATEGORIA = 'NACIONAL') THEN
            RETURN SELF.SALARIO * 1.15;
        ELSIF (SELF.CATEGORIA = 'OPERACIONES ESPECIALES') THEN
            RETURN SELF.SALARIO * 1.20;
        ELSE
            RETURN SELF.SALARIO;
        END IF;
    END calculaSalario;
END;




CREATE TABLE POLICIAS OF POLICIA;
cREATE TABLE RESPONSABLES OF INSPECTOR;

SET SERVEROUTPUT ON;
DECLARE 
POLI1 POLICIA;
POLI2 POLICIA;
POLI3 POLICIA;

salarioFinal number;
salario number(4);

BEGIN 

POLI1 := NEW POLICIA ('12345678L','PEDRO','LOPEZ','GARCIA',666999666, 'LOCAL', 1500);
POLI2 := NEW POLICIA ('89217933L','MARTIN','LOPEZ','MARQUEZ',666995666, 'NACIONAL', 1700);

POLI3 := NEW POLICIA ('98745632O','MARC','GALLEGO','GARCIA',666999866, 'OPERACIONES ESPECIALES', 1800);

DBMS_OUTPUT.PUT_LINE(POLI1.TELEFONO);
DBMS_OUTPUT.PUT_LINE(POLI2.NOMBRE);
DBMS_OUTPUT.PUT_LINE(POLI3.DNI);

salario:= poli2.salario;

salarioFinal := poli2.calculaSalario(salario);

DBMS_OUTPUT.PUT_LINE(salarioFinal);

END;









